### PR TITLE
suggested fixes for issues #61, #62

### PR DESCRIPTION
**Pull request by tilt12345678**

### CODE REVIEW

**Comment by fbt** [comment]
I have to disagree with the sane defaults one.

PREFIX=/ is not a sane default. Installing stuff around your package manager in /usr/local helps keeping your system tidy. And packagers set the vars to their needs anyway.

**Comment by tilt12345678** [comment]
hi that one is of course site-specific, that's why i reverted it :D i hope?

**Comment by fbt** [comment]
Oh. Commenting on issues drunk after work is not productive. I have not noticed that you've reverted it. Sorry.

**Comment by jcnelson** [comment]
@tilt12345678 Thanks for sending this as a PR!  Merged :)

**Pull request merged**
